artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL : https://github.com/deepankarthikdjk/github_data_repo/raw/main/winequality.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion

# define configuration settings related to data ingestion, specifically for downloading and handling a dataset.
# artifacts_root: Specifies the root directory where artifacts (e.g., downloaded data, models, etc.) will be stored.
# data_ingestion: Defines settings related to data ingestion.
# root_dir: Specifies the root directory for data ingestion artifacts within the artifacts_root.
# source_URL: Specifies the URL from which the data will be downloaded.
# local_data_file: Specifies the local file path where the downloaded data will be stored.
# unzip_dir: Specifies the directory where the downloaded data will be unzipped.